
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

export const SUPABASE_URL = "https://uagckghgdqmioejsopzv.supabase.co";
export const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVhZ2NrZ2hnZHFtaW9lanNvcHp2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyNjIzNDcsImV4cCI6MjA2MDgzODM0N30.wR2Dvyg9YAFwgwuHgHet5LlacS2YLulvDFZ4YVpBXP8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
